### ISSUE TITLE
It keeps refusing my Github account.

### ISSUE THREAD

**Issue by TetragrammatonHermit** [brookhong/cloudboard.vim#1]
Pretty much tried putting my email address, then username. It simply is not allowing me to register so I can't take advantage. Thanks.

Forgot to add it says, "Invalid Github account"

**Comment by brookhong** [comment]
It should be username plus password if you have a github account.

And if you would not like to use your github account, you can just use your email address as an identifier.

**Comment by brookhong** [comment]
I finally reproduced this issue, it caused by below changes.
Now, the plugin will require user to input token directly.

https://developer.github.com/v3/oauth_authorizations/

```
The token attribute is deprecated in all of the following OAuth Authorizations API responses:

List your authorizations
```
